### ISSUE TITLE
Multiselect: the number of options to select and message bubble

### ISSUE THREAD

**Issue by antonxt** [Cognigy/WebchatPlugins#103]
I have a few ideas on improving `Multiselect`:

1. A message bubble is always shown above the Open Button even if the message is null or empty text. It doesn't look good when it is empty, I suggest to simply hide it.
2. It would be very practical if the number of options, which the user can/must select, can be specified. E.g. `selectAtLeast`, `selectAtMost`. Now the user can select none or select all options.
3. After the user had used the select and the flow moved on, the user can open the select again and submit one more time. I suggest disabling the button to avoid this.
4. It would be nice to see the value(s) selected as a message from the user, similarly to how Rating does it.

Also, `README.md` can be improved by adding a real-life example of a message, e.g.:

```js
const payload = {
    _plugin: {
        type: 'multiselect',
        allowUserAnswers: false,
        cancelButtonLabel: 'Cancel',
        inputPlaceholder: 'Enter Time',
        options: ['10:00', '10:30', '11:00', '11:45', '12:15'],
        openButtonLabel: 'Choose Time',
        submitButtonLabel: 'Submit'
    }
}
api.say('Select Time', payload)
```

**Comment by ArpitSvam** [comment]
@antonxt  Sorry, this is probably not the right place to ask this question, but I'm not sure where else I could ask.
I've been trying to use the multi-select plugin but I couldn't find a way to store the selected options in any variable that would be available in Cognigy (like input, state, context, etc.). How do we use the selected options from the multi-select form.
Any help would be greatly appreciated.

**Comment by antonxt** [comment]
@ArpitSvam, the plugin submits the selected values in the data part of the message from the user. You will receive them in `input.data` in your flow. See in action [here](https://webchat-trial.cognigy.ai/v2/88920d2e55f89f8ab497d77c9f1fbed103c33982f0ec341aa4b13c2c183d02cf)

For this purprose, however, I recommend [Adaptive Cards](https://adaptivecards.io/samples/) as they allow much more flexibility in user input form design. Cognigy now natively supports Output Type = Adaptive Card in its Say and Question nodes. The webchat also supports them natively, you don't need a plugin any longer. Microsoft Teams channel also renders them well.

**Comment by antonxt** [comment]
This request doesn't make much sense any longer because Adaptive Cards offer better support for collecting multivalued user inputs, so I am closing my request
