### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by jagadish20** [Cognigy/WebchatPlugins#16]
Hi,

After adding the map plugin only pointer is displaying, background map is not displaying.

**Comment by mayrbenjamin92** [comment]
Hi Jagadish,

our Webchat plugins are open source and MIT licensed! Feel free to just fix the problem on your own. These plugins are not part of our core product and hence we do not really support them. They are meant as an inspiration for you to extend our platform and our Webchat experience.

Any pull request to this repository is welcome!

Best regards,
Benni
