### ISSUE TITLE
GoogleMaps

### ISSUE THREAD

**Issue by lucawiesmann** [Cognigy/WebchatPlugins#51]
![problem google maps plugin](https://user-images.githubusercontent.com/61311520/88806224-6f4d2f00-d1b0-11ea-9314-c38554a214ca.PNG)

![problem 2](https://user-images.githubusercontent.com/61311520/88806643-f8646600-d1b0-11ea-87bd-8f9e4a83c02a.PNG)

The Google Maps Plugin isn't working properly in my google chrome webbrowser.

Google Chrome version: 84.0.4147.105 (Offizieller Build) (64-Bit)

What could be my issue?

**Comment by AlexTeusz** [comment]
Hey @lucawiesmann ,
thank you. We will fix this.
