### ISSUE TITLE
rating: should not submit empty values

### ISSUE THREAD

**Issue by antonxt** [Cognigy/WebchatPlugins#75]
<img width="463" alt="ss" src="https://user-images.githubusercontent.com/7406247/106819837-68d1cf80-668b-11eb-8fbb-776ca294ed8c.png">

Possible solution: the Send Rating button can be disabled before the user enters any rating. Or we can allow the user to explicitly avoid entering any rating by e.g. adding a "Skip" button.

**Comment by AlexTeusz** [comment]
This is solved with the new release 1.1.1
